server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: 264
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "c8dac67a7a065bdd5e6743134b81f3468a204b5bcd4f0acfe62a8fb22dc1a639"